// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-imxmEsN1YhoR_DO2p5Zt5WfGhqikeF0',
    appId: '1:88150142578:web:6d5ff976d0ee290eeb5ceb',
    messagingSenderId: '88150142578',
    projectId: 'fitway-app-cad65',
    authDomain: 'fitway-app-cad65.firebaseapp.com',
    storageBucket: 'fitway-app-cad65.appspot.com',
    measurementId: 'G-GZ6HLC6EHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBATZHFFx-6nf7h5X1WZquwiwhTM0Vmx-U',
    appId: '1:88150142578:android:eeb2b04529102a37eb5ceb',
    messagingSenderId: '88150142578',
    projectId: 'fitway-app-cad65',
    storageBucket: 'fitway-app-cad65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkaDmEv6Recfh_t7IuXzVlBvFnYWYTyuE',
    appId: '1:88150142578:ios:cd6b68fff1035ba7eb5ceb',
    messagingSenderId: '88150142578',
    projectId: 'fitway-app-cad65',
    storageBucket: 'fitway-app-cad65.appspot.com',
    iosBundleId: 'com.brunocardozo.com.fitwayapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkaDmEv6Recfh_t7IuXzVlBvFnYWYTyuE',
    appId: '1:88150142578:ios:cd6b68fff1035ba7eb5ceb',
    messagingSenderId: '88150142578',
    projectId: 'fitway-app-cad65',
    storageBucket: 'fitway-app-cad65.appspot.com',
    iosBundleId: 'com.brunocardozo.com.fitwayapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-imxmEsN1YhoR_DO2p5Zt5WfGhqikeF0',
    appId: '1:88150142578:web:76e2f9f61acaf0d8eb5ceb',
    messagingSenderId: '88150142578',
    projectId: 'fitway-app-cad65',
    authDomain: 'fitway-app-cad65.firebaseapp.com',
    storageBucket: 'fitway-app-cad65.appspot.com',
    measurementId: 'G-GQ3WSNL1X4',
  );

}